server:
  port: 9200
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ribbon-demo
          uri: lb://RIBBON-DEMO
          predicates:
            - Path=/ribbon/**
          filters:
            - StripPrefix=1
        - id: feign-demo
          uri: lb://FEIGN-DEMO
          predicates:
            - Path=/feign/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug