server:
  port: 9100
spring:
  application:
    name: zuul-demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
zuul:
  routes:
    apiRibbon:
      path: /api/ribbon/**
      serviceId: ribbon-demo
    apiFeign:
      path: /api/feign/**
      serviceId: feign-demo
#\u7194\u65ADhystrix\u8D85\u65F6\u914D\u7F6E(\u9ED8\u8BA4\u914D\u7F6E\u5F88\u5BB9\u6613\u89E6\u53D1 Gateway Timeout \u5F02\u5E38)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#ribbon\u8D85\u65F6\u914D\u7F6E
#ReadTimeout: \u7528\u6765\u8BBE\u7F6E\u8DEF\u7531\u8F6C\u53D1\u8BF7\u6C42\u7684\u8D85\u65F6\u65F6\u95F4
#ConnectTimeout: \u7528\u6765\u8BBE\u7F6E\u8DEF\u7531\u8F6C\u53D1\u8BF7\u6C42\u7684\u65F6\u5019\uFF0C\u521B\u5EFA\u8BF7\u6C42\u8FDE\u63A5\u7684\u8D85\u65F6\u65F6\u95F4
#MaxAutoRetries: \u5BF9\u5F53\u524D\u5B9E\u4F8B\u7684\u91CD\u8BD5\u6B21\u6570
#MaxAutoRetriesNextServer: \u5207\u6362\u5B9E\u4F8B\u7684\u91CD\u8BD5\u6B21\u6570
#ribbon:
#  ReadTimeout: 50000
#  ConnectTimeout: 50000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1